// This program uses hashing to access / insert / delete data.
// The  problem of collision is not resolved.
// Author: Vikas Nagpal : http://anuttaralearning.com/
  
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_STR_LENGTH 20
#define HASH_TBL_SIZE 10  //Hash Table Size // Note: normally, it is prime!

/* Structure to store employee details */
typedef struct employee_info
{
  int   id;
  char  name[MAX_STR_LENGTH];
  char  group[MAX_STR_LENGTH];
} employee_info_t;

/* Function Prototypes */
int hash_function(int id);
void insert(int emp_id, char *emp_name, char *emp_group, employee_info_t employee[]);
void delete (int emp_id, employee_info_t employee[]);
void search(int emp_id, employee_info_t employee[]);
void display(employee_info_t employee[]);

/* Main Function */
int main(int argc, char *argv[])
{
  // Current approach : Hash Table directory storing the struct (and not pointer to data)
  employee_info_t employee[HASH_TBL_SIZE]; //Hash Table

  memset(employee, 0, sizeof(employee));

  printf("Inserting John(5), Kevin(4) and Ricky(15)\n");
  insert(5, "John", "Engg", employee);
  insert(4, "kevin", "IT", employee);
  insert(15, "Ricky", "FIN", employee);

  printf("Searching for id 15\n");
  search(15, employee);
  printf("Searching for id 5\n");
  search(5, employee);
  display(employee);

  printf("\n\n");

 
  printf("Deleting id(s) 15 and 4\n");
  delete(15, employee);
  delete(4, employee);
  display(employee);
  return 0;
}

/***********************************************************************************
  Function inserts the employee details at the index generated by the hash function.
  Collision is not yet handled.
***********************************************************************************/
void insert(int emp_id, char *emp_name, char *emp_group, employee_info_t employee[])
{
  int index;
  index = hash_function(emp_id); 
  if(0 == employee[index].id) // id 0 means hash table slot is free
  {
    printf("Inserting at index %d\n",index);
    employee[index].id = emp_id;
    strcpy(employee[index].name, emp_name);
    strcpy(employee[index].group, emp_group);
  }
  else // Collision
    printf("Collision at index %d... Can not insert...\n",index);
}

/***********************************************************************************
  Function deletes the employee details of the employee id from the hash table.
***********************************************************************************/
void delete (int emp_id, employee_info_t employee[])
{
  int index;
  index = hash_function(emp_id);

  /* Check if the employee info at that index is empty */
  if(emp_id != employee[index].id)
  {
    printf("No entry in Hash Table for emp_id=%d\n", emp_id);
  }
  else
  {
    printf("Deleted emp_id=%d from index %d\n", emp_id, index);
    /* Removing the information from table */
    employee[index].id = 0;
    // Note: strictly speaking, below initialization not needed. setting id=0 is enough
    memset(employee[index].name, 0, sizeof(employee[index].name));
    memset(employee[index].group, 0, sizeof(employee[index].group));
  }
}
/***********************************************************************************
  Function searches the employee details of the employee id from the hash table.
***********************************************************************************/
void search(int emp_id, employee_info_t employee[])
{
  int index;

  index = hash_function(emp_id);

  /* Check if the employee info at that index is empty */
  if (emp_id != employee[index].id)
  {
    printf("No entry in Hash Table for emp_id=%d\n", emp_id);
  }
  else
  {
    printf("Found emp_id=%d at index %d\n", emp_id, index);
    printf("%d\t\t%s\t\t%s\n", employee[index].id, employee[index].name, employee[index].group);
  }
}

/***********************************************************************************
  Function displays the hash table.
***********************************************************************************/
void display(employee_info_t employee[])
{
  int index;
  printf("Employee id \tEmployee name \t Employee group\n");
  printf("-----------------------------------------------------\n");
  for(index = 0;index < HASH_TBL_SIZE; index++)
    printf("%d\t\t%s\t\t%s\n",employee[index].id,employee[index].name,employee[index].group);
}

/*************************************************************
    Hash computing function
  Parameter : Employee id
  Returns   : an index in the table
*************************************************************/
int hash_function(int id)
{
  return id % HASH_TBL_SIZE;
}
